### Vectors

Characteristics:
 - Dimensionality - number of numbers in a vector
 - Oreintation - is the vector row or col oriented
    * Generally assumed to be in col form unless specified
    * Row form vectors are written as w^T where T = transpose

Dimensions are MxN or (M, N) where M = row and N = col

In [7]:
import numpy as np


asList = [1,2,3,4]

asArray = np.array(asList)
print(asArray, '\n', asArray.shape, '\n\n')

rowVec = np.array([asList])
print(rowVec, '\n', rowVec.shape, '\n\n')

colVec = np.array([ [i] for i in asList])
print(colVec, '\n', colVec.shape, '\n\n')

[1 2 3 4] 
 (4,) 


[[1 2 3 4]] 
 (1, 4) 


[[1]
 [2]
 [3]
 [4]] 
 (4, 1) 




In [36]:
# Vector Operations

x = np.arange(0, 10)
x_reshaped = x.reshape((10, 1))

y = np.arange(10, 20)
y_reshaped = y.reshape((10, 1))

# print(x, y)

# Addition
# print(x_reshaped + y_reshaped)

# Subtraction
# print(x_reshaped - y_reshaped)

arrA = np.array([1,2,3])
arrB = np.array([4,5,6])
arrBCol = arrB.reshape((3,1))

# Broadcasting -> More Detail Later
print(arrA + arrBCol, '\n')

# Vector - Scalar Oprations
sample_scalar = 10
print(sample_scalar * arrA, '\n')


# Vector Averaging
print(arrA + arrB * 0.5, '\n')

# Transposing
print(arrA.T.shape, arrA.shape)

[[5 6 7]
 [6 7 8]
 [7 8 9]] 

[10 20 30] 

[3.  4.5 6. ] 

(3,) (3,)
